chapters:
- chapters: []
  folderName: main
  name: puzzlesCloudMDs
  path: README.md
  sourceURL: https://github.com/milance1998/puzzlesCloudMDs.git
  type: MARKDOWN_CHAPTER
- chapters: []
  folderName: main
  name: Big
  path: big.md
  sourceURL: https://github.com/milance1998/puzzlesCloudMDs.git
  type: MARKDOWN_CHAPTER
- chapters:
  - chapters: []
    folderName: main
    name: puzzlesCloudMDs
    path: image200kbtest.md
    sourceURL: https://github.com/milance1998/puzzlesCloudMDs.git
    type: MARKDOWN_CHAPTER
  - chapters: []
    folderName: main
    name: Images
    path: images.md
    sourceURL: https://github.com/milance1998/puzzlesCloudMDs.git
    type: MARKDOWN_CHAPTER
  - chapters: []
    folderName: ''
    name: testerko
    path: ''
    sourceURL: ''
    type: MANUAL_CHAPTER
  - chapters: []
    folderName: main
    name: puzzlesCloudMDs
    path: READMEtest222.md
    sourceURL: https://github.com/milance1998/puzzlesCloudMDs.git
    type: MARKDOWN_CHAPTER
  folderName: ''
  name: testerkoh1
  path: ''
  sourceURL: ''
  type: MANUAL_CHAPTER
fieldValues:
  doc-release-date: ''
  doc-type: ''
  doc-title: ''
  File Name: prodtest2.docx
  doc-version: ''
folderName: null
name: ROOT
path: null
sourceURL: null
type: null
